name: Create NuGet Package
on: 
  pull_request:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - uses: actions/checkout@v2
      - run: dotnet --version